# Generated by Django 2.2.5 on 2020-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0002_user_auth_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bag_size',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
