# Generated by Django 2.2.5 on 2020-05-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0005_auto_20200413_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
