# Generated by Django 2.2.5 on 2020-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0006_auto_20200502_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='coffee_type',
            new_name='origin',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
