# Generated by Django 2.2.5 on 2020-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0008_auto_20200502_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bag_size',
            field=models.CharField(default='12oz', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
