# Generated by Django 2.2.5 on 2020-05-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0009_auto_20200502_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='subscription_id',
        ),
        migrations.CreateModel(
            name='Subscription_item',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('roaster_name', models.CharField(max_length=80)),
                ('bean_status', models.CharField(default='Whole', max_length=15)),
                ('note', models.CharField(max_length=255, null=True)),
                ('product_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lrc.Product')),
                ('subscription_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lrc.Subscription')),
            ],
        ),
    ]
