# Generated by Django 2.2.5 on 2020-05-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0012_auto_20200502_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roaster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
