# Generated by Django 2.2.5 on 2020-05-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrc', '0014_auto_20200531_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_rotation_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address_two',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
